### ISSUE TITLE
Friendly landing page

### ISSUE THREAD

**Issue by jsms90** [CYPIAPT-LNDSE/anxiety-ladder#4]
As a young person suffering from anxiety
I want to see a friendly landing page
So that I feel comfortable facing my fears and encouraged to use the app

**Comment by ishiar** [comment]
not sure if comments help, ... so I just randomly provide feedback context, thanks for great issues!
'friendly' is the great word for it, the service user will hate doing what they have to practice, imagine you felt an anxiety 90/100 (100 is you collapse/highest fear you could ever imagine..) which often is the case..
