### ISSUE TITLE
Login - necessary in order to access my own ladders

### ISSUE THREAD

**Issue by jsms90** [CYPIAPT-LNDSE/anxiety-ladder#5]
As a young person suffering from anxiety
I want to log into my account
So that I can see MY ladders and have ownership over the process

**Comment by ishiar** [comment]
think that is great, maybe there is an option to remain logged in, imagine when you are out on exposure practice - you would want to rate it at the beginning, do what you have to do for about 20min, then rate/document as soon as possible...

**Comment by jsms90** [comment]
@ishiar Yes, that's a good point.

On the [readme](https://github.com/foundersandcoders/anxiety-ladder/blob/master/README.md) we have separated the two user journeys:
- Creating a ladder
- Reviewing a ladder

We do have this idea of remaining logged in for the "Reviewing ladder" user journey
> I should be able to remain logged in by default... So that I can review the exposure exercise as easily as possible...

because remaining logged in a feature that's most important, as you said, when the young person is reviewing an exposure practice.

For this sprint, we are focusing on building a prototype for the "create ladder" user journey. But we will definitely be explaining how this can be expanded upon to include the "reviewing ladder" user journey in our presentation :+1:

It seems like we might have 3 journeys:
+ Create a ladder - setting an anxiety rating
+ Start an exposure practice - re-rating based on how they feel as they are about to start
+ Review the practice - re-rating based on how they feel after completing the exposure task

Does that sound right?

**Comment by ishiar** [comment]
@jsms90 I'm not quite certain about whether we are talking about the same thing when talking about reviewing:

1."Create a ladder - setting an anxiety rating" - agree, sometimes you might edit this ladder(add a challenging situation for having an in between step or re-rate the anxiety on the ladder sometimes you don't
2. Start an exposure practice - re-rating based on how they feel as they are about to start" - you would not re-rate the challenge on the ladder when you do the practice, you would create an extra rating that is not connected to the rating of the challenge itself. Imagine you set up the goal of a ladder about "want to do the way to school by myself'. you add challenging situations e.g. 1. oyster card check in in the bus, 70/100, 2. arriving at the school gate 65/100, 3. walking along the street in front of my house 45/100. the ratings are theoretical ratings. the yp sets them up by thinking about the expected anxiety. once you practice, you set your rating by fact, by being in the situation, once before, once after. that can differ completely from the ladder set up. so the data you produce during your practice, that is the important bit, as it is observing the change in the ratings what helps you to try and tackle the harder ones. does that make sense?

**Comment by jsms90** [comment]
@ishiar Thanks for clarifying. It's good to always make sure we're on the same page.

This may just have been bad wording on my part. I wasn't intending "re-rating" in the sense of replacing the initial, "theoretical" rating. I was thinking "re-rating" just in the sense that they are doing the process again. It would be these "extra" ratings (before and after) that were then stored by the app, and eventually put onto a graph of some kind.

Does that sound right?

**Comment by ishiar** [comment]
@jsms90 brilliant, thanks thats it!
