### ISSUE TITLE
Slider bar for anxiety rating

### ISSUE THREAD

**Issue by jsms90** [CYPIAPT-LNDSE/anxiety-ladder#9]
As a young person suffering from anxiety
I want to rate each step in a non-numerical way
So that my rating is less calculated and more instinctive and hence doesn't cause added anxiety

+ [x] Find a nice slider component
+ [ ] Figure out why the slider is visible on my comp but not Will's #36

**Comment by ishiar** [comment]
for some of the ocd YPs this is awsome to not see numbers! on the other hand it's really helpful to be able to somehow understand the difference of what makes me very/less anxious in the end... numbers make it easy to talk about, but hard for some YPs. ...maybe the difference could be seen in the graphs?..

**Comment by MHemsley** [comment]
@ishiar @jsms90  ways we've done this previously is discreet values (e.g. going up in single numbers 1,2,3), having a UI that fedback these discreet steps and leave out the numbers. This tested relatively well with those with moderate/past experience of OCD and those with severe anxiety

**Comment by jsms90** [comment]
@MHemsley Interesting! The reason for making this choice was purely down to some of the direct user feedback from an OCD app that I worked on in the past.
But I have seen online that the vast majority of material on exposure ladders do seem to have discrete numbers. So it may be just an isolated few who experience this? I would happily bow to your experience, and change it to a 1-10 or 1-100 number scale if you think that's better?

@ishiar Given that the ladder will re-order the challenges based on their anxiety ratings, that should provide some pretty direct feedback to our users, about which challenges cause them more anxiety.

But it wouldn't give them anything to be able to compare their ratings between different ladders. Numbers definitely do make it easier to talk about. We've been trying to think of other ways of presenting this information, without potentially putting off those who may not like the choice displayed as discrete numbers.

Trying to keep it visual, we thought about:
+ a colour scale
  + our immediate thought was green to red, but I'm sure that seeing a lot of red could have a negative impact
  + shades of one colour? This might work: lighter = calmer
+ keep the colourless slider, but the slider bar itself is a smiley face, going from happy/calm expression to anxious expression?

**Comment by ishiar** [comment]
@jsms90 it's a difficult one indeed, as the OCD kids might have an issue with it but panic/anxiety might profit from having a tool to distance themselves a bit by being factual in a description... regarding smileys:I was thinking about this morning if I should issue an issue called sth like 'as a yp with anxiety I want graphics and information as factual as possible so that I can focus on a very horrible task effectively.'.. I try and get feedback from OCD/panic/anxiety folks in the clinic tmrw morning

**Comment by ishiar** [comment]
@jsms90 I had a chat with one of the clinicians who does a lot of OCD/panic/anxiety work. She said she actually takes along a sheet of paper which has a number system as a basis, smileys above and color code below. she said the YPs who have ocd issues with one scale were able to ignore that scale and were able to focus on the one they prefer. so I wonder if there was a solution similar to that where we integrate a verbal with a non-verbal scale?..

**Comment by jsms90** [comment]
@ishiar Unfortunately, I think we have to make a choice for the app just because of space.
Unless we were to have a separate web page, just for the anxiety ratings?
